// VIDALOZZI — Contenu du blog (bilingue FR / EN)
// ─────────────────────────────────────────────────────────────────────────
// Chaque article : { slug, category{fr,en}, dateISO, readMin, hero,
//   fr: { title, dek, body[] }, en: { title, dek, body[] } }
// Types de blocs supportés : { type:"p", text } · { type:"h2", text }
//   · { type:"ul", items[] } · { type:"ol", items[] } · { type:"quote", text }
// PUBLICATION AUTO : chaque article devient visible le jour de sa "dateISO"
//   (AAAA-MM-JJ). Avant, il est masqué de la liste + passe en noindex. Rien à faire.
//   Pour publier maintenant : dateISO <= aujourd'hui. Pour repousser : date future.
// ─────────────────────────────────────────────────────────────────────────

window.BLOG_POSTS = [
  {
    slug: "ugc-convertit-mieux-que-pub-classique",
    category: { fr: "Stratégie", en: "Strategy" },
    dateISO: "2026-04-28",
    readMin: 8,
    hero: "UGC / PERFORMANCE",
    fr: {
      title: "Pourquoi le contenu UGC convertit mieux que la pub classique en 2026",
      dek: "La publicité léchée ne ressemble plus à rien de ce que vos clients regardent. Voici pourquoi le contenu créateur reprend la main sur la performance — et ce que ça change pour vos budgets paid.",
      body: [
        { type: "p", text: "Une marque a deux secondes pour convaincre un utilisateur de ne pas faire défiler. Dans cette fenêtre, une publicité de studio — éclairage parfait, voix-off corporate, logo en ouverture — envoie un signal immédiat : « ceci est une pub ». Et le cerveau, entraîné par des années de scroll, l'écarte avant même de l'avoir comprise." },
        { type: "p", text: "Le contenu UGC fait l'inverse. Il ressemble à ce que regarde déjà l'utilisateur : une personne réelle, un cadre familier, un ton parlé. Le temps que le cerveau identifie qu'il s'agit d'une publicité, le message est déjà passé." },
        { type: "p", text: "Cette bascule n'est plus une expérimentation : pour la majorité des marques DTC, e-commerce et SaaS B2C qui scalent sur Meta et TikTok en 2026, l'UGC est devenu le format pivot des comptes paid. Ce qui suit explique pourquoi, ce que vous pouvez en attendre concrètement, et comment lancer un premier test sans transformer votre budget créa en pari." },
        { type: "h2", text: "Le « pattern interrupt » natif" },
        { type: "p", text: "Sur TikTok, Reels ou Shorts, la grammaire visuelle est très codifiée : vertical, caméra à la main, lumière naturelle, montage rapide. Une pub qui respecte cette grammaire ne casse pas l'expérience — elle la prolonge. C'est tout l'enjeu du native advertising, et l'UGC est le format le plus natif qui existe." },
        { type: "p", text: "Ce n'est pas qu'une intuition. Les marques qui passent d'un asset « studio » à un asset UGC sur la même audience observent presque systématiquement un meilleur taux de rétention sur les trois premières secondes — la métrique qui détermine si l'algorithme va, ou non, continuer à diffuser." },
        { type: "p", text: "Et c'est là que le levier se compose : un meilleur hook fait baisser le CPM, fait monter le taux de lecture, et l'algorithme interprète ces signaux comme une preuve de pertinence. Vous ne payez pas seulement moins cher l'impression suivante — vous obtenez aussi une diffusion plus large auprès de profils que vous n'auriez pas atteints en ciblant manuellement." },
        { type: "ul", items: [
          "Cadre vertical 9:16, tourné caméra à la main.",
          "Première seconde parlée par une personne face caméra.",
          "Sous-titres brûlés, lecture sans le son possible.",
          "Aucun logo ni jingle dans les trois premières secondes.",
        ]},
        { type: "h2", text: "La confiance prime sur la production" },
        { type: "p", text: "Le consommateur de 2026 est devenu son propre directeur marketing. Il lit les avis, compare, attend la preuve avant l'argument. Un témoignage filmé par une personne qui semble ne rien vendre vaut plus qu'un spot impeccable qui sent l'agence." },
        { type: "quote", text: "On n'achète plus une promesse de marque. On achète l'expérience de quelqu'un qui nous ressemble." },
        { type: "p", text: "C'est ce déplacement — de la promesse à la preuve — qui explique la performance de l'UGC. Le format ne crée pas la confiance par magie : il crée le contexte dans lequel la confiance devient possible." },
        { type: "p", text: "Pour vous, deux conséquences pratiques. La première touche le casting : un créateur crédible dans le quotidien de votre audience cible vaut mieux qu'un visage parfait mais hors-sol. La seconde touche le brief : plus vous laissez d'espace au créateur pour formuler le bénéfice avec ses propres mots, plus l'asset sonne juste. Un brief verrouillé mot pour mot produit une pub déguisée — visible en deux secondes, et écartée aussi vite." },
        { type: "h2", text: "Le volume créatif, vrai moteur du paid" },
        { type: "p", text: "Sur Meta comme sur TikTok, la performance dépend moins d'un asset parfait que de la capacité à tester vite et large. La fatigue créative tue les campagnes : un visuel qui marche s'épuise en deux à trois semaines, parfois moins quand l'audience est restreinte, et la fréquence d'exposition fait remonter le CPA jusqu'à inverser la rentabilité." },
        { type: "p", text: "L'UGC résout ce problème par construction. Un même brief produit facilement plusieurs hooks, plusieurs angles, plusieurs formats — à une fraction du coût d'une production traditionnelle. Vous ne pariez plus sur une création : vous alimentez une machine à itérer." },
        { type: "ul", items: [
          "Coût par asset réduit — donc plus de variations testables.",
          "Renouvellement rapide pour contrer la fatigue créative.",
          "Des données d'apprentissage plus riches pour l'algorithme.",
        ]},
        { type: "p", text: "Concrètement, un mois d'UGC bien cadré, c'est rarement « une vidéo ». C'est plutôt trois créateurs, six à neuf vidéos brutes, et autant de variantes de hook et de montage que votre média buyer peut absorber. Au lieu de chercher la création parfaite, vous laissez l'algorithme désigner les deux ou trois angles qui sortent du lot, puis vous concentrez le budget dessus." },
        { type: "h2", text: "Ce que disent les chiffres en pratique" },
        { type: "p", text: "Les benchmarks publics sur l'UGC sont à manier avec prudence : ils mélangent verticales, prix moyen panier et niveaux de maturité de compte très différents. Les ordres de grandeur observés chez les marques DTC qui passent d'une logique « studio » à une logique « UGC volume » sont néanmoins constants : un taux de hook à 3 secondes qui passe d'environ 25-30 % à 40-50 %, un CPM en baisse modérée mais durable, et surtout un nombre de créas « gagnantes » par mois multiplié par trois ou quatre." },
        { type: "p", text: "Le ROAS, lui, bouge rarement de façon spectaculaire sur une seule créa. Ce qui bouge, c'est la stabilité : moins de cycles d'effondrement quand l'asset gagnant s'épuise, parce qu'il y en a toujours un autre prêt à prendre le relais. La métrique à suivre n'est donc pas « le ROAS de la vidéo X », mais le nombre de créas qui passent le seuil de rentabilité chaque mois." },
        { type: "p", text: "C'est ce changement de référentiel — d'une mesure par asset à une mesure par flux — qui distingue les comptes qui scalent de ceux qui plafonnent." },
        { type: "h2", text: "Quand l'UGC sous-performe" },
        { type: "p", text: "Refuser l'effet de mode commence par admettre les cas où l'UGC n'est pas le bon levier. Sur certains produits B2B très techniques avec un cycle de décision long, le format ne crée pas de raccourci : la preuve passe ailleurs — démo, étude de cas, livre blanc. Sur les marques de luxe, le code de catégorie suppose une production maîtrisée ; un asset trop « brut » peut éroder le positionnement plus qu'il ne convertit." },
        { type: "p", text: "Et même sur les verticales où l'UGC est performant, il échoue quand le brief est trop scripté ou quand le casting trahit l'audience. Un créateur qui ne consomme pas le produit qu'il présente s'entend en trois mots, et l'algorithme s'en rend compte aussi vite que votre prospect." },
        { type: "ul", items: [
          "Cycle de vente long avec validation comité — l'UGC seul ne suffit pas.",
          "Catégorie où la production fait partie de la promesse de marque.",
          "Brief trop verrouillé, créateur récitant un script sans naturel.",
        ]},
        { type: "h2", text: "Comment lancer un test sans cramer le budget" },
        { type: "p", text: "Le piège classique consiste à commander une seule vidéo à un seul créateur, à la lancer sur une campagne large, et à conclure quoi que ce soit du résultat. Un test UGC qui apprend vraiment quelque chose tient en cinq étapes." },
        { type: "ol", items: [
          "Cadrer une seule offre, un seul produit, une seule promesse à valider.",
          "Choisir deux ou trois angles différents — pas deux variantes du même angle.",
          "Caster un créateur par angle, en priorité un profil qui ressemble à votre cible plutôt qu'un profil qui flatte la marque.",
          "Produire un brief court, orienté objectifs et points clés, qui laisse la formulation au créateur.",
          "Tester en advantage+ ou audience large sur une période suffisante pour atteindre un seuil de signaux exploitables avant de couper.",
        ]},
        { type: "p", text: "Côté budget, un test honnête se chiffre rarement en dizaines d'euros. Comptez plutôt l'équivalent d'une à deux semaines de votre dépense paid habituelle dédiée au test, avec un nombre de conversions cible défini à l'avance. Sans ce seuil, vous prendrez une décision sur du bruit." },
        { type: "h2", text: "Ce que ça change pour vous" },
        { type: "p", text: "Arrêter d'opposer « image de marque » et « performance ». L'UGC bien pensé fait les deux : il convertit aujourd'hui et nourrit la familiarité de marque sur la durée. La vraie question n'est plus « faut-il faire de l'UGC ? » mais « combien de variations puis-je tester ce mois-ci, et avec quels créateurs ? »." },
        { type: "p", text: "Si vous voulez en discuter pour vos propres campagnes, le plus simple reste un appel de quinze minutes — on regarde votre produit, votre cible, et on définit deux ou trois angles à tester avant la fin du mois." },
      ],
    },
    en: {
      title: "Why UGC converts better than traditional advertising in 2026",
      dek: "Polished advertising no longer looks like anything your customers actually watch. Here's why creator content is taking back performance — and what it changes for your paid budgets.",
      body: [
        { type: "p", text: "A brand has two seconds to convince a user not to scroll. In that window, a studio ad — perfect lighting, corporate voiceover, logo on the open — sends an instant signal: \"this is an ad.\" And the brain, trained by years of scrolling, dismisses it before it has even processed it." },
        { type: "p", text: "UGC does the opposite. It looks like what the user is already watching: a real person, a familiar setting, a spoken tone. By the time the brain realises it's an ad, the message has already landed." },
        { type: "p", text: "This shift is no longer an experiment: for most DTC, e-commerce and B2C SaaS brands scaling on Meta and TikTok in 2026, UGC has become the pivot format of the paid account. What follows explains why, what you can expect in practice, and how to launch a first test without turning your creative budget into a gamble." },
        { type: "h2", text: "The native pattern interrupt" },
        { type: "p", text: "On TikTok, Reels or Shorts, the visual grammar is highly codified: vertical, handheld, natural light, fast cuts. An ad that respects this grammar doesn't break the experience — it extends it. That's the whole point of native advertising, and UGC is the most native format there is." },
        { type: "p", text: "This isn't just intuition. Brands that move from a studio asset to a UGC asset on the same audience almost always see better three-second retention — the metric that decides whether the algorithm keeps serving the ad." },
        { type: "p", text: "That's where the leverage compounds: a better hook lowers your CPM, lifts your view-through rate, and the algorithm reads those signals as relevance. You don't just pay less for the next impression — you reach profiles you couldn't have targeted manually, because the platform extends distribution on its own." },
        { type: "ul", items: [
          "Vertical 9:16 frame, shot handheld.",
          "First second spoken by a person on camera.",
          "Burned-in subtitles, watchable without sound.",
          "No logo or jingle in the first three seconds.",
        ]},
        { type: "h2", text: "Trust beats production value" },
        { type: "p", text: "The 2026 consumer has become their own marketing director. They read reviews, compare, expect proof before the pitch. A testimonial filmed by someone who seems to be selling nothing is worth more than a flawless spot that reeks of agency." },
        { type: "quote", text: "People no longer buy a brand promise. They buy the experience of someone who looks like them." },
        { type: "p", text: "That shift — from promise to proof — is what explains UGC's performance. The format doesn't create trust by magic: it creates the context in which trust becomes possible." },
        { type: "p", text: "Two practical consequences. The first is about casting: a creator who fits the daily life of your target audience beats a polished face that feels out of context. The second is about briefing: the more room you leave for the creator to phrase the benefit in their own words, the more the asset rings true. A word-for-word locked brief produces a disguised ad — spotted in two seconds, scrolled past just as fast." },
        { type: "h2", text: "Creative volume, the real paid engine" },
        { type: "p", text: "On Meta and TikTok alike, performance depends less on one perfect asset than on the ability to test fast and wide. Creative fatigue kills campaigns: a winning visual burns out in two to three weeks, sometimes less on narrow audiences, and rising frequency pushes the CPA up until profitability flips." },
        { type: "p", text: "UGC solves this by design. A single brief easily yields several hooks, angles and formats — at a fraction of the cost of traditional production. You're no longer betting on one creative: you're feeding an iteration machine." },
        { type: "ul", items: [
          "Lower cost per asset — so more testable variations.",
          "Fast refresh to counter creative fatigue.",
          "Richer learning data for the algorithm.",
        ]},
        { type: "p", text: "In practice, one month of well-framed UGC is rarely \"one video.\" It looks more like three creators, six to nine raw videos, and as many hook and edit variants as your media buyer can absorb. Instead of hunting for the perfect creative, you let the algorithm surface the two or three angles that pull away, then concentrate budget on those." },
        { type: "h2", text: "What the numbers actually look like" },
        { type: "p", text: "Public benchmarks on UGC should be handled carefully: they mix verticals, average order values and account maturity levels that aren't comparable. That said, the orders of magnitude observed when DTC brands move from a \"studio\" logic to a \"UGC volume\" logic are remarkably consistent: a three-second hook rate climbing from roughly 25-30% to 40-50%, a moderate but durable CPM drop, and — above all — a number of winning creatives per month multiplied by three or four." },
        { type: "p", text: "ROAS itself rarely moves dramatically on a single creative. What moves is stability: fewer collapse cycles when the winning asset burns out, because another one is ready to take over. The metric to track is not \"the ROAS of video X,\" it's the number of creatives that cross the profitability threshold each month." },
        { type: "p", text: "That shift of reference — from a per-asset measure to a per-flow measure — is what separates accounts that scale from accounts that plateau." },
        { type: "h2", text: "When UGC underperforms" },
        { type: "p", text: "Refusing the hype starts with admitting the cases where UGC isn't the right lever. On highly technical B2B products with a long decision cycle, the format doesn't create a shortcut: proof lives elsewhere — demo, case study, white paper. On luxury brands, the category code assumes mastered production; an asset that feels too \"raw\" can erode positioning more than it converts." },
        { type: "p", text: "And even in verticals where UGC performs, it fails when the brief is over-scripted or when the casting betrays the audience. A creator who doesn't actually use the product they introduce gives themselves away in three words, and the algorithm picks it up as fast as your prospect does." },
        { type: "ul", items: [
          "Long sales cycle with committee approval — UGC alone won't carry it.",
          "Category where production is part of the brand promise.",
          "Locked brief, creator reciting a script with no naturalness.",
        ]},
        { type: "h2", text: "How to launch a test without burning the budget" },
        { type: "p", text: "The classic trap is ordering a single video from a single creator, running it on a broad campaign, and drawing any conclusion from the result. A UGC test that actually teaches you something fits in five steps." },
        { type: "ol", items: [
          "Frame a single offer, a single product, a single promise to validate.",
          "Pick two or three different angles — not two variants of the same angle.",
          "Cast one creator per angle, prioritising profiles that look like your target rather than profiles that flatter the brand.",
          "Write a short brief, focused on objectives and key points, that leaves wording to the creator.",
          "Run on advantage+ or broad audience long enough to reach a usable signal threshold before cutting.",
        ]},
        { type: "p", text: "On budget: an honest test rarely costs a token amount. Plan for the equivalent of one to two weeks of your usual paid spend dedicated to the test, with a target conversion count defined upfront. Without that threshold, you'll make a decision on noise." },
        { type: "h2", text: "What it changes for you" },
        { type: "p", text: "Stop pitting \"brand\" against \"performance.\" Well-conceived UGC does both: it converts today and builds brand familiarity over time. The real question is no longer \"should we do UGC?\" but \"how many variations can I test this month, and with which creators?\"" },
        { type: "p", text: "If you want to talk it through for your own campaigns, the simplest path is a fifteen-minute call — we look at your product, your audience, and define two or three angles to test before the end of the month." },
      ],
    },
  },

  {
    slug: "prix-createur-ugc-france",
    category: { fr: "Tarifs", en: "Pricing" },
    dateISO: "2026-05-12",
    readMin: 9,
    hero: "TARIFS / 2026",
    fr: {
      title: "Combien coûte vraiment un créateur UGC en France ?",
      dek: "Entre les freelances à 80 € la vidéo et les agences à plusieurs milliers d'euros, le marché est opaque. Décryptage honnête de ce que vous payez, et pourquoi.",
      body: [
        { type: "p", text: "C'est la première question de toute marque, et la plus mal répondue. Une recherche rapide donne des fourchettes allant de 50 € à 2 000 € pour « une vidéo UGC ». Cet écart n'est pas du hasard : il recouvre des prestations qui n'ont rien à voir entre elles." },
        { type: "p", text: "Le problème, quand on découvre le marché de l'UGC en France, c'est qu'aucun chiffre n'a vraiment de sens isolé. Deux devis affichant le même montant peuvent couvrir des périmètres opposés ; deux devis à un facteur dix de différence peuvent livrer un résultat équivalent à l'écran. L'enjeu n'est donc pas de connaître « le prix », mais de savoir lire ce qu'il y a derrière." },
        { type: "p", text: "Cet article décrit la structure réelle d'un tarif UGC en France en 2026 : ce qui se cache dans la ligne « vidéo », les vraies fourchettes du marché, et la grille de questions à poser avant de signer un devis." },
        { type: "h2", text: "Pourquoi le prix d'un créateur UGC paraît si opaque" },
        { type: "p", text: "Le marché français de l'UGC est jeune. Il n'a ni grille tarifaire syndicale, ni intermédiaire dominant qui imposerait un standard. Les créateurs viennent de profils très différents — comédiens, monteurs, influenceurs, étudiants — et chacun chiffre selon son propre référentiel : taux journalier, prix au livrable, royalties paid, ou simple intuition." },
        { type: "p", text: "Côté demande, l'acheteur est tout aussi divers : une marque DTC qui sort sa première campagne, une agence média qui industrialise pour ses clients, un retailer qui veut nourrir ses fiches produit. Chacune valorise différemment le concept, l'exclusivité, les droits, le casting. D'où des écarts qui semblent absurdes vus de l'extérieur, mais qui répondent à des logiques d'achat opposées." },
        { type: "p", text: "La conséquence, pour vous : comparer deux devis sans avoir clarifié l'usage prévu, le volume cible et la durée d'exploitation revient à comparer un café à emporter et un menu gastronomique parce que les deux contiennent du café." },
        { type: "h2", text: "Ce que vous payez réellement" },
        { type: "p", text: "Le prix d'une vidéo UGC n'est jamais « le prix du tournage ». C'est la somme de plusieurs postes que les devis low-cost masquent souvent :" },
        { type: "ul", items: [
          "La conception : angle, hook, script. Le vrai travail créatif.",
          "Le tournage : matériel, lumière, plusieurs prises, plusieurs hooks.",
          "Le montage : rythme, sous-titres, étalonnage, formats.",
          "Les droits : usage organique seul, ou diffusion paid — et pour combien de temps.",
          "Les retakes : combien de reprises sont incluses, dans quel délai.",
        ]},
        { type: "p", text: "Une vidéo à 80 € ne contient en général que le tournage brut, sans droits paid. Le jour où vous voulez la pousser en publicité, vous découvrez que ce n'était pas prévu — et la facture grimpe, ou pire, vous diffusez sans droits." },
        { type: "p", text: "Les droits paid sont, et de loin, le poste le plus mal compris. Un usage organique sur les comptes de la marque coûte une chose ; une diffusion sponsorisée sur Meta ou TikTok pendant six mois, avec spark ads et white-listing, en coûte une autre — généralement deux à trois fois plus. Quand le devis ne précise pas, il faut considérer que les droits paid ne sont pas inclus." },
        { type: "h2", text: "Les fourchettes du marché en France en 2026" },
        { type: "p", text: "En France, en 2026, on observe globalement trois niveaux :" },
        { type: "ul", items: [
          "Débutant / micro-freelance : 60–150 € la vidéo. Exécution simple, peu ou pas de droits, qualité variable.",
          "Créateur établi : 300–700 € la vidéo, dégressif au volume. Concept inclus, droits paid négociables.",
          "Agence / production : 1 500 € et plus par concept, avec stratégie, casting et gestion de campagne.",
        ]},
        { type: "p", text: "Ces fourchettes recouvrent une réalité simple : un débutant facture son temps de tournage ; un créateur établi facture le résultat ; une agence facture une délégation complète. À chaque niveau correspond une responsabilité différente sur l'angle, le risque créatif, et la performance attendue." },
        { type: "p", text: "Pour une marque qui démarre, le bon réflexe n'est pas d'aller au moins cher ni au plus cher, mais de calibrer le niveau au niveau de maturité de votre compte paid. Si vous n'avez pas encore d'audience suffisante pour distinguer un asset gagnant d'un asset moyen, payer 2 000 € pour une production léchée est gaspillé. Si vous cherchez à scaler un compte qui tourne déjà, payer 80 € pour un tournage brut sans droits est un faux raccourci." },
        { type: "quote", text: "Le moins cher au coup n'est presque jamais le moins cher au résultat." },
        { type: "h2", text: "Combien coûte une campagne, pas juste une vidéo" },
        { type: "p", text: "Acheter « une vidéo UGC » est rarement la bonne unité d'achat. Sur Meta et TikTok, ce qui fait baisser le coût par acquisition n'est pas la créa unique, mais le flux de variations : plusieurs angles, plusieurs hooks, plusieurs montages d'un même contenu source." },
        { type: "p", text: "Pour une marque qui veut un effet mesurable sur ses campagnes paid, un budget mensuel UGC réaliste se situe entre 1 500 et 5 000 €, selon le rythme de production. Cela correspond à trois à six créateurs sollicités sur le mois, six à douze vidéos brutes, et plusieurs dizaines de variantes une fois le déclinement de hooks et de formats fait." },
        { type: "p", text: "Sous ce seuil, vous achetez des assets isolés — utiles, mais difficiles à comparer entre eux faute de volume statistique. Au-dessus, vous entrez dans la logique « machine à itérer » qui justifie l'investissement par la baisse durable du CPA." },
        { type: "h2", text: "Le coût caché : le coût d'opportunité" },
        { type: "p", text: "Une vidéo bon marché qui ne convertit pas vous coûte deux fois : le prix de la vidéo, et le budget média gaspillé à la diffuser. À l'inverse, un asset à 500 € qui baisse votre coût par acquisition de 20 % se rembourse en quelques jours de diffusion." },
        { type: "p", text: "Faites le calcul sur vos propres chiffres. Si vous dépensez 10 000 € par mois en paid et que votre CPA actuel est de 25 €, gagner 15 % sur ce CPA vaut environ 1 500 € de marge récupérée — soit largement de quoi payer trois à cinq vidéos UGC de qualité. Le ROI ne se mesure pas sur le prix du livrable, il se mesure sur l'écart de performance entre l'avant et l'après." },
        { type: "p", text: "C'est pour ça que raisonner « prix à la vidéo » est un piège. La bonne unité, c'est le coût par asset performant — et là, l'expérience et la qualité du brief pèsent bien plus que le tarif affiché." },
        { type: "h2", text: "Comment bien acheter" },
        { type: "ol", items: [
          "Demandez systématiquement ce que les droits paid couvrent, et pour quelle durée.",
          "Privilégiez les packs multi-vidéos : le coût unitaire baisse et vous avez de quoi tester.",
          "Vérifiez si le concept et le script sont inclus, ou facturés en plus.",
          "Méfiez-vous des prix sans devis : un bon créateur cadre le périmètre avant de chiffrer.",
          "Comparez ce qui est comparable : même brief, même nombre de hooks, mêmes droits.",
        ]},
        { type: "p", text: "Et surtout, ne réduisez pas la décision au tarif horaire ou au prix unitaire. Un créateur qui prend deux fois plus pour livrer une vidéo réellement testée et déjà optimisée pour vos campagnes vous fera économiser, sur l'année, beaucoup plus que la différence." },
        { type: "h2", text: "Les questions à poser avant de signer un devis" },
        { type: "p", text: "Si vous ne devez retenir qu'une chose : faites poser au prestataire les questions ci-dessous avant de comparer les tarifs. Un devis sans réponse claire à ces six points ne vaut pas la peine d'être comparé." },
        { type: "ul", items: [
          "Les droits paid sont-ils inclus, et pour quelle durée d'exploitation ?",
          "Combien de hooks et de variantes de montage sont livrés par vidéo source ?",
          "Le concept (angle, script, structure) est-il inclus ou facturé à part ?",
          "Combien de retakes sont prévues, et sous quel délai ?",
          "L'usage en spark ads ou white-listing est-il autorisé ?",
          "À qui appartient la matière brute (rushes), et peut-on la réutiliser ?",
        ]},
        { type: "p", text: "Pour référence, mes propres formules vont de l'exécution simple sur votre brief jusqu'au partenariat de campagne complet, droits inclus. Le détail est sur la page UGC — et pour un chiffrage précis sur votre besoin, un appel suffit." },
      ],
    },
    en: {
      title: "What does a UGC creator really cost in France?",
      dek: "Between freelancers at €80 a video and agencies at several thousand euros, the market is opaque. An honest breakdown of what you're paying for, and why.",
      body: [
        { type: "p", text: "It's every brand's first question, and the worst answered. A quick search returns ranges from €50 to €2,000 for \"a UGC video.\" That gap isn't random: it covers services that have nothing in common." },
        { type: "p", text: "The hard part, when you first explore the UGC market in France, is that no single number means anything in isolation. Two quotes showing the same amount can cover opposite scopes; two quotes a factor of ten apart can deliver an equivalent on-screen result. The question isn't \"what's the price\" — it's whether you can read what sits behind it." },
        { type: "p", text: "This article breaks down the real structure of a UGC quote in France in 2026: what hides in the \"video\" line item, the actual market ranges, and the checklist of questions to ask before signing." },
        { type: "h2", text: "Why UGC creator pricing feels so opaque" },
        { type: "p", text: "The French UGC market is young. It has no union pricing grid and no dominant intermediary setting a standard. Creators come from very different backgrounds — actors, editors, influencers, students — and each prices against their own reference: day rate, per-deliverable, paid royalties, or simple intuition." },
        { type: "p", text: "On the demand side, buyers are just as varied: a DTC brand launching its first campaign, a media agency industrialising for clients, a retailer feeding product pages. Each one values concept, exclusivity, rights and casting differently. Hence gaps that look absurd from the outside but follow opposite buying logics." },
        { type: "p", text: "The consequence, for you: comparing two quotes without first clarifying the intended use, the target volume and the exploitation duration is like comparing a takeaway coffee and a tasting menu because both involve coffee." },
        { type: "h2", text: "What you're actually paying for" },
        { type: "p", text: "The price of a UGC video is never just \"the cost of the shoot.\" It's the sum of several line items that low-cost quotes often hide:" },
        { type: "ul", items: [
          "Conception: angle, hook, script. The real creative work.",
          "Shooting: gear, lighting, multiple takes, multiple hooks.",
          "Editing: pacing, subtitles, color grade, formats.",
          "Rights: organic use only, or paid distribution — and for how long.",
          "Retakes: how many revisions are included, within what window.",
        ]},
        { type: "p", text: "An €80 video usually contains only the raw shoot, no paid rights. The day you want to push it as an ad, you discover it wasn't included — and the bill climbs, or worse, you run it without rights." },
        { type: "p", text: "Paid rights are, by far, the most misunderstood line item. Organic use on the brand's owned channels costs one thing; sponsored distribution on Meta or TikTok for six months, with spark ads and white-listing, costs another — usually two to three times more. When a quote doesn't specify, assume paid rights are not included." },
        { type: "h2", text: "France market ranges in 2026" },
        { type: "p", text: "In France, in 2026, you'll broadly find three tiers:" },
        { type: "ul", items: [
          "Beginner / micro-freelance: €60–150 a video. Simple execution, little or no rights, variable quality.",
          "Established creator: €300–700 a video, scaling down with volume. Concept included, paid rights negotiable.",
          "Agency / production: €1,500 and up per concept, with strategy, casting and campaign management.",
        ]},
        { type: "p", text: "Behind these tiers, a simple truth: a beginner charges for their shoot time; an established creator charges for the result; an agency charges for a full delegation. Each tier carries a different responsibility on angle, creative risk and expected performance." },
        { type: "p", text: "For a brand starting out, the right instinct isn't to pick the cheapest or the most expensive, but to match the tier to your paid account's maturity. If you don't yet have enough audience to tell a winning asset from an average one, paying €2,000 for a polished production is wasted. If you're scaling an account that's already working, paying €80 for a rights-less raw shoot is a false shortcut." },
        { type: "quote", text: "The cheapest per video is almost never the cheapest per result." },
        { type: "h2", text: "What a campaign costs, not just a video" },
        { type: "p", text: "Buying \"a UGC video\" is rarely the right unit. On Meta and TikTok, what brings your cost per acquisition down isn't a single creative — it's the flow of variations: several angles, several hooks, several edits of the same source." },
        { type: "p", text: "For a brand looking for measurable impact on its paid campaigns, a realistic monthly UGC budget sits between €1,500 and €5,000, depending on production cadence. That covers three to six creators activated in the month, six to twelve raw videos, and dozens of variants once hooks and formats are declined." },
        { type: "p", text: "Below that threshold, you're buying isolated assets — useful, but hard to compare to each other without statistical volume. Above it, you're entering the \"iteration machine\" logic that justifies the spend through a durable CPA drop." },
        { type: "h2", text: "The hidden cost: opportunity cost" },
        { type: "p", text: "A cheap video that doesn't convert costs you twice: the price of the video, and the media budget wasted serving it. Conversely, a €500 asset that cuts your cost per acquisition by 20% pays for itself in a few days of spend." },
        { type: "p", text: "Do the math on your own numbers. If you spend €10,000 a month in paid and your current CPA is €25, gaining 15% on that CPA is worth around €1,500 of recovered margin — comfortably enough to pay for three to five quality UGC videos. ROI isn't measured on the deliverable price; it's measured on the performance gap between before and after." },
        { type: "p", text: "That's why thinking \"price per video\" is a trap. The right unit is cost per performing asset — and there, experience and brief quality matter far more than the headline rate." },
        { type: "h2", text: "How to buy well" },
        { type: "ol", items: [
          "Always ask what the paid rights cover, and for how long.",
          "Favor multi-video packs: unit cost drops and you have enough to test.",
          "Check whether concept and script are included, or billed on top.",
          "Be wary of prices with no quote: a good creator scopes the work before pricing it.",
          "Compare like for like: same brief, same number of hooks, same rights.",
        ]},
        { type: "p", text: "Above all, don't reduce the decision to an hourly rate or unit price. A creator who charges twice as much but delivers a video that's actually tested and pre-optimised for your campaigns will save you, over a year, much more than the difference." },
        { type: "h2", text: "Questions to ask before signing a quote" },
        { type: "p", text: "If you remember one thing: make the supplier answer the questions below before comparing rates. A quote without clear answers on these six points isn't worth comparing." },
        { type: "ul", items: [
          "Are paid rights included, and for what exploitation duration?",
          "How many hooks and edit variants are delivered per source video?",
          "Is the concept (angle, script, structure) included or billed separately?",
          "How many retakes are planned, within what timeframe?",
          "Is use in spark ads or white-listing authorised?",
          "Who owns the raw footage, and can it be reused?",
        ]},
        { type: "p", text: "For reference, my own packages run from simple execution on your brief to a full campaign partnership with rights included. The detail is on the UGC page — and for a precise quote on your need, a call is enough." },
      ],
    },
  },

  {
    slug: "erreurs-brief-ugc",
    category: { fr: "Méthode", en: "Method" },
    dateISO: "2026-06-24",
    readMin: 5,
    hero: "BRIEF / MÉTHODE",
    fr: {
      title: "Brief UGC : les erreurs qui font rater vos campagnes",
      dek: "Un mauvais brief produit un bon créateur incapable de bien travailler. Les cinq erreurs les plus fréquentes, et comment les éviter avant de lancer.",
      body: [
        { type: "p", text: "Quand une vidéo UGC déçoit, on accuse souvent le créateur. Dans la majorité des cas, le problème est en amont : le brief. Un créateur ne devine pas vos objectifs — il exécute ce qu'on lui donne. Voici les cinq erreurs qui plombent le résultat avant même le tournage." },
        { type: "h2", text: "1. Confondre objectif et format" },
        { type: "p", text: "« On veut une vidéo de 30 secondes » n'est pas un objectif. « On veut baisser notre coût par achat sur une audience froide » en est un. Le format découle de l'objectif, jamais l'inverse. Sans intention claire, le créateur optimise au hasard." },
        { type: "h2", text: "2. Ne pas fournir d'angle" },
        { type: "p", text: "L'angle, c'est la promesse centrale de la vidéo : le problème qu'on attaque, la raison d'acheter qu'on met en avant. Un brief sans angle force le créateur à inventer le vôtre — et il connaît moins bien votre client que vous." },
        { type: "quote", text: "Un brief sans angle, c'est demander un itinéraire sans donner la destination." },
        { type: "h2", text: "3. Sur-scripter chaque mot" },
        { type: "p", text: "L'excès inverse est tout aussi nocif. Un script verrouillé phrase par phrase tue le naturel — qui est précisément ce qui fait fonctionner l'UGC. Donnez les points de passage obligés et la promesse ; laissez le ton au créateur." },
        { type: "h2", text: "4. Oublier le hook" },
        { type: "p", text: "Les trois premières secondes décident de tout. Pourtant, beaucoup de briefs détaillent le produit et oublient l'accroche. Demandez systématiquement deux à trois hooks alternatifs : c'est la variable la plus rentable à tester." },
        { type: "h2", text: "5. Ne rien dire sur la diffusion" },
        { type: "p", text: "Une vidéo pour du paid froid, une vidéo pour du retargeting et une vidéo organique ne se construisent pas pareil. Préciser où la vidéo sera diffusée change le rythme, le CTA et la longueur. C'est souvent l'information manquante la plus coûteuse." },
        { type: "h2", text: "Le bon réflexe" },
        { type: "p", text: "Un bon brief tient sur une page : objectif business, audience, angle, deux ou trois hooks souhaités, contraintes de marque, et plan de diffusion. Rien de plus. Si vous voulez un modèle prêt à remplir, j'en ai écrit un — il est dans un autre article du journal." },
      ],
    },
    en: {
      title: "UGC briefs: the mistakes that sink your campaigns",
      dek: "A bad brief turns a good creator into someone who can't do good work. The five most common mistakes, and how to avoid them before you launch.",
      body: [
        { type: "p", text: "When a UGC video disappoints, the creator usually gets the blame. In most cases the problem is upstream: the brief. A creator doesn't guess your goals — they execute what they're given. Here are the five mistakes that wreck the result before the shoot even starts." },
        { type: "h2", text: "1. Confusing goal with format" },
        { type: "p", text: "\"We want a 30-second video\" is not a goal. \"We want to lower our cost per purchase on a cold audience\" is. Format follows from the goal, never the other way around. Without a clear intention, the creator optimises at random." },
        { type: "h2", text: "2. Providing no angle" },
        { type: "p", text: "The angle is the video's central promise: the problem you attack, the reason to buy you put forward. A brief with no angle forces the creator to invent yours — and they know your customer less well than you do." },
        { type: "quote", text: "A brief with no angle is asking for directions without naming the destination." },
        { type: "h2", text: "3. Over-scripting every word" },
        { type: "p", text: "The opposite excess is just as harmful. A script locked sentence by sentence kills the naturalness — which is exactly what makes UGC work. Give the mandatory beats and the promise; leave the tone to the creator." },
        { type: "h2", text: "4. Forgetting the hook" },
        { type: "p", text: "The first three seconds decide everything. Yet many briefs detail the product and forget the opener. Always ask for two or three alternative hooks: it's the most profitable variable to test." },
        { type: "h2", text: "5. Saying nothing about distribution" },
        { type: "p", text: "A video for cold paid, a video for retargeting and an organic video aren't built the same way. Specifying where the video will run changes the pace, the CTA and the length. It's often the most expensive missing piece of information." },
        { type: "h2", text: "The right reflex" },
        { type: "p", text: "A good brief fits on one page: business goal, audience, angle, two or three desired hooks, brand constraints, and a distribution plan. Nothing more. If you want a fill-in-the-blanks template, I wrote one — it's in another journal article." },
      ],
    },
  },

  {
    slug: "ugc-vs-influenceur",
    category: { fr: "Comparatif", en: "Comparison" },
    dateISO: "2026-05-26",
    readMin: 7,
    hero: "UGC vs INFLUENCE",
    fr: {
      title: "UGC vs influenceur : lequel choisir pour votre budget ?",
      dek: "Les deux mettent en scène des personnes réelles, mais ne vendent pas la même chose. L'un vous loue une audience, l'autre vous livre un asset. Comment trancher.",
      body: [
        { type: "p", text: "On les confond souvent, parce que les deux reposent sur des personnes filmant des produits. Pourtant, l'UGC et l'influence répondent à des logiques opposées. Choisir le mauvais, c'est payer cher pour le mauvais résultat." },
        { type: "p", text: "La confusion est entretenue par les plateformes elles-mêmes : Instagram, TikTok, YouTube ne distinguent pas les deux dans leurs outils créateurs. Et beaucoup d'agences vendent indifféremment l'un pour l'autre, en jouant sur l'ambiguïté du livrable. Résultat : des marques qui paient un format pour en obtenir un autre, ou qui mesurent leur retour sur le mauvais indicateur." },
        { type: "p", text: "Ce qui suit clarifie la différence sur trois plans : ce que vous achetez réellement, quand chaque format est pertinent, et comment calculer le ROI avant de signer. À la fin, vous saurez précisément lequel choisir pour votre budget — ou pourquoi les deux peuvent cohabiter." },
        { type: "h2", text: "Ce que vous achetez réellement" },
        { type: "p", text: "Avec un influenceur, vous payez une audience : sa communauté, sa portée, sa crédibilité auprès de ses abonnés. Le livrable, c'est une publication sur son compte, vue par ses abonnés, à un instant donné." },
        { type: "p", text: "Avec un créateur UGC, vous payez un asset : une vidéo dont vous êtes propriétaire, que vous diffusez vous-même, sur vos canaux, avec votre budget média. Le créateur n'a pas besoin d'audience — il a besoin de savoir filmer et convaincre." },
        { type: "quote", text: "L'influence loue une audience. L'UGC vous livre une matière première." },
        { type: "p", text: "Cette différence change tout en aval : la propriété du contenu, la durée d'exploitation, les droits paid, et surtout la façon dont vous mesurez la performance. Un post d'influenceur se mesure en portée et engagement organique. Un asset UGC se mesure en CPM, taux de hook, et ROAS de campagne. Deux référentiels, deux métiers." },
        { type: "h2", text: "Tableau comparatif : UGC vs influence" },
        { type: "p", text: "Pour résumer la différence sur les critères qui pèsent le plus dans une décision d'achat :" },
        { type: "ul", items: [
          "Livrable — UGC : vidéo brute que vous montez et diffusez. Influence : publication finie sur le compte du créateur.",
          "Propriété — UGC : la marque possède l'asset. Influence : le créateur garde son post.",
          "Diffusion — UGC : illimitée, sur vos canaux et vos budgets paid. Influence : limitée à l'audience du compte au moment du post.",
          "Mesure — UGC : ROAS, CPA, taux de hook par variante. Influence : portée, vues, engagement, parfois ventes via code promo.",
          "Coût type — UGC : 200–700 € la vidéo en France. Influence : 200 € à 10 000 € le post selon l'audience.",
          "Durée de vie — UGC : plusieurs mois, déclinable en variantes. Influence : pic sur 24–72 h, puis quasi nul.",
          "Risque — UGC : faible (asset livré, vous décidez de la diffusion). Influence : élevé (résultat dépend de l'algorithme du compte tiers).",
        ]},
        { type: "h2", text: "Quand choisir l'influence" },
        { type: "p", text: "L'influence garde un sens précis et puissant — mais sur des objectifs bien définis. Choisissez-la quand :" },
        { type: "ul", items: [
          "Vous visez la notoriété et la preuve sociale auprès d'une communauté précise.",
          "Le compte de l'influenceur a une vraie résonance avec votre cible.",
          "Vous acceptez de ne pas maîtriser totalement le message ni la diffusion.",
          "Vous lancez un produit qui a besoin d'un effet de mode ou d'un signal social fort.",
          "Vous pouvez vous permettre de payer pour de la visibilité sans demande de conversion directe.",
        ]},
        { type: "p", text: "L'erreur classique consiste à acheter de l'influence pour des objectifs de performance pure. Une publication sponsorisée éphémère ne nourrit pas un compte paid, ne vous laisse pas d'asset réutilisable, et ne se mesure pas sur le CPA. Si l'objectif est de baisser le coût d'acquisition, l'influence est rarement le bon levier." },
        { type: "h2", text: "Quand choisir l'UGC" },
        { type: "p", text: "L'UGC est le bon outil dès qu'il y a un compte paid à nourrir ou une fiche produit à enrichir. Concrètement :" },
        { type: "ul", items: [
          "Vous voulez nourrir vos campagnes paid avec des assets que vous contrôlez.",
          "Vous avez besoin de volume et de variations pour tester.",
          "Vous voulez réutiliser le contenu sur la durée, sans dépendre d'un compte tiers.",
          "Vous cherchez à baisser votre CPA Meta ou TikTok de manière mesurable.",
          "Vous opérez une marque DTC ou e-commerce avec scaling progressif des dépenses paid.",
        ]},
        { type: "p", text: "L'UGC est aussi le seul format qui s'industrialise : vous pouvez activer trois créateurs en parallèle ce mois-ci, six le mois prochain, sans renégocier à chaque fois les codes éditoriaux. C'est cette scalabilité qui fait sa différence stratégique." },
        { type: "h2", text: "La question du budget" },
        { type: "p", text: "Un post d'influenceur à audience moyenne (50 000 à 200 000 abonnés en France) se négocie souvent entre 1 500 et 5 000 € — pour une diffusion unique, qui plafonne à quelques dizaines de milliers de vues organiques. À budget équivalent, vous obtiendrez entre cinq et dix vidéos UGC, exploitables pendant plusieurs mois sur vos comptes paid." },
        { type: "p", text: "Pour un budget contraint orienté performance, l'UGC offre presque toujours un meilleur rendement : vous payez la création une fois, vous diffusez autant de fois que nécessaire. Et chaque euro de média ajouté amplifie un asset que vous contrôlez, sans renégocier les droits ni dépendre de l'algorithme d'un tiers." },
        { type: "h2", text: "Le calcul de ROI à faire avant de signer" },
        { type: "p", text: "Avant de choisir entre les deux, faites le calcul rapide qui aligne le format à l'objectif. Sur une page de papier :" },
        { type: "ol", items: [
          "Quel est mon objectif principal : notoriété, considération, ou conversion directe ?",
          "Combien d'impressions ou de visites le format va-t-il me donner, et à quel coût par mille ?",
          "L'asset livré est-il réutilisable ailleurs sans renégocier ?",
          "Quel est le coût d'acquisition cible, et lequel des deux formats a le plus de chances de l'atteindre ?",
        ]},
        { type: "p", text: "Dans neuf cas sur dix pour une marque DTC ou un e-commerce, les réponses orientent vers l'UGC. Dans le dixième — lancement événementiel, marque émergente cherchant à exister culturellement — l'influence reste pertinente." },
        { type: "h2", text: "Le faux dilemme" },
        { type: "p", text: "Les marques les plus matures ne choisissent pas : elles utilisent l'influence pour la notoriété et l'UGC pour la conversion. Mais quand il faut prioriser un budget serré sur la performance, commencez par l'UGC — c'est le levier le plus contrôlable et le plus mesurable." },
        { type: "p", text: "Une fois l'UGC stabilisé et un CPA cible atteint, vous pouvez réintroduire de l'influence pour amplifier la notoriété — sans dépendre d'elle pour vos ventes. C'est dans cet ordre, et pas l'inverse, que les marques construisent une présence durable. Si vous voulez en discuter pour votre cas, le plus simple reste un appel de quinze minutes." },
      ],
    },
    en: {
      title: "UGC vs influencer: which to choose for your budget?",
      dek: "Both feature real people, but they don't sell the same thing. One rents you an audience, the other hands you an asset. How to decide.",
      body: [
        { type: "p", text: "They're often confused, because both rest on people filming products. Yet UGC and influence answer opposite logics. Pick the wrong one and you pay a lot for the wrong result." },
        { type: "p", text: "The confusion is fed by the platforms themselves: Instagram, TikTok and YouTube don't distinguish the two in their creator tools. And many agencies sell either as the other, leaning on the ambiguity. The outcome: brands paying for one format and getting the other, or measuring their return against the wrong indicator." },
        { type: "p", text: "What follows clarifies the difference on three fronts: what you're actually buying, when each format is relevant, and how to calculate ROI before signing. By the end, you'll know exactly which to pick for your budget — or why both can coexist." },
        { type: "h2", text: "What you're actually buying" },
        { type: "p", text: "With an influencer, you pay for an audience: their community, their reach, their credibility with their followers. The deliverable is a post on their account, seen by their followers, at a given moment." },
        { type: "p", text: "With a UGC creator, you pay for an asset: a video you own, that you distribute yourself, on your channels, with your media budget. The creator needs no audience — they need to know how to film and convince." },
        { type: "quote", text: "Influence rents an audience. UGC hands you raw material." },
        { type: "p", text: "This difference cascades downstream: content ownership, exploitation period, paid rights, and above all how you measure performance. An influencer post is measured in reach and organic engagement. A UGC asset is measured in CPM, hook rate, and campaign ROAS. Two reference systems, two jobs." },
        { type: "h2", text: "Comparison table: UGC vs influence" },
        { type: "p", text: "To sum up the difference on the criteria that weigh most in a buying decision:" },
        { type: "ul", items: [
          "Deliverable — UGC: raw video you edit and distribute. Influence: finished post on the creator's account.",
          "Ownership — UGC: the brand owns the asset. Influence: the creator keeps their post.",
          "Distribution — UGC: unlimited, across your channels and your paid budgets. Influence: limited to the account's audience at the time of posting.",
          "Measurement — UGC: ROAS, CPA, hook rate per variant. Influence: reach, views, engagement, sometimes sales via promo code.",
          "Typical cost — UGC: €200–700 per video in France. Influence: €200 to €10,000 per post depending on audience.",
          "Lifespan — UGC: several months, declinable into variants. Influence: spike over 24–72h, then near zero.",
          "Risk — UGC: low (asset delivered, you decide the distribution). Influence: high (results depend on the third party's algorithm).",
        ]},
        { type: "h2", text: "When to choose influence" },
        { type: "p", text: "Influence still has precise, powerful uses — but on clearly defined goals. Choose it when:" },
        { type: "ul", items: [
          "You're after awareness and social proof with a specific community.",
          "The influencer's account genuinely resonates with your target.",
          "You accept not fully controlling the message or distribution.",
          "You're launching a product that needs a fashion effect or a strong social signal.",
          "You can afford to pay for visibility without demanding direct conversion.",
        ]},
        { type: "p", text: "The classic mistake is buying influence for pure performance goals. An ephemeral sponsored post doesn't feed a paid account, doesn't leave you a reusable asset, and doesn't measure on CPA. If the goal is to lower acquisition cost, influence is rarely the right lever." },
        { type: "h2", text: "When to choose UGC" },
        { type: "p", text: "UGC is the right tool whenever there's a paid account to feed or a product page to enrich. Concretely:" },
        { type: "ul", items: [
          "You want to feed your paid campaigns with assets you control.",
          "You need volume and variations to test.",
          "You want to reuse content over time, without depending on a third-party account.",
          "You're looking to lower your Meta or TikTok CPA in a measurable way.",
          "You operate a DTC or e-commerce brand with progressive paid scaling.",
        ]},
        { type: "p", text: "UGC is also the only format that industrialises: you can activate three creators in parallel this month, six next month, without renegotiating editorial codes every time. That scalability is its strategic edge." },
        { type: "h2", text: "The budget question" },
        { type: "p", text: "A mid-audience influencer post (50,000 to 200,000 followers in France) usually negotiates between €1,500 and €5,000 — for a single airing that tops out at a few tens of thousands of organic views. For the same budget, you'll get five to ten UGC videos, usable for months across your paid accounts." },
        { type: "p", text: "For a constrained, performance-focused budget, UGC almost always offers a better return: you pay for creation once, you distribute as many times as needed. And each added euro of media amplifies an asset you control, without renegotiating rights or depending on a third party's algorithm." },
        { type: "h2", text: "The ROI math to do before signing" },
        { type: "p", text: "Before choosing between the two, run the quick calculation that aligns format to goal. On one page:" },
        { type: "ol", items: [
          "What's my main goal: awareness, consideration, or direct conversion?",
          "How many impressions or visits will the format give me, at what CPM?",
          "Is the delivered asset reusable elsewhere without renegotiation?",
          "What's my target acquisition cost, and which format is more likely to hit it?",
        ]},
        { type: "p", text: "In nine out of ten cases for a DTC brand or e-commerce, the answers point to UGC. In the tenth — event launch, emerging brand seeking cultural existence — influence remains relevant." },
        { type: "h2", text: "The false dilemma" },
        { type: "p", text: "The most mature brands don't choose: they use influence for awareness and UGC for conversion. But when a tight budget must be prioritised on performance, start with UGC — it's the most controllable and measurable lever." },
        { type: "p", text: "Once UGC is stable and a target CPA is hit, you can layer influence back in to amplify awareness — without depending on it for sales. That's the order, not the reverse, in which brands build durable presence. If you want to talk through your case, the simplest path is a fifteen-minute call." },
      ],
    },
  },

  {
    slug: "choisir-createur-ugc",
    category: { fr: "Méthode", en: "Method" },
    dateISO: "2026-06-10",
    readMin: 7,
    hero: "CASTING / CRÉATEUR",
    fr: {
      title: "Comment choisir son créateur UGC sans se planter",
      dek: "Le nombre d'abonnés ne dit rien de la qualité d'un créateur UGC. Voici les vrais critères à regarder avant de signer un brief.",
      body: [
        { type: "p", text: "Le marché de l'UGC a explosé, et avec lui le nombre de profils qui se présentent comme créateurs. Tous ne se valent pas — et les signaux qui comptent ne sont pas ceux qu'on regarde en premier. Voici comment trier." },
        { type: "p", text: "La plupart des erreurs de casting tiennent à un malentendu : on cherche un créateur UGC comme on cherchait un influenceur il y a cinq ans, avec les mêmes réflexes (abonnés, esthétique du compte, engagement). Or les deux métiers ne se mesurent pas avec les mêmes signaux. Ce qui fait la différence n'est pas la portée, c'est la capacité à produire des assets qui performent en publicité." },
        { type: "p", text: "Ce guide passe en revue les critères réels — typologie des profils que vous croiserez en France, qualités à tester dans un portfolio, signaux qui doivent vous faire fuir — pour que vous puissiez choisir un créateur UGC qui crée de la valeur, pas de la frustration." },
        { type: "h2", text: "Les trois profils de créateurs UGC que vous allez croiser en France" },
        { type: "p", text: "Avant de regarder un portfolio, situez le profil. En France en 2026, trois grandes familles se partagent le marché, et chacune répond à des besoins différents." },
        { type: "ul", items: [
          "Le créateur-comédien : vient du jeu d'acteur, à l'aise face caméra, fort sur la diction et l'émotion. Idéal pour le témoignage, la démo parlée, la promesse sincère.",
          "Le créateur-monteur : vient de la post-production, fort sur le rythme, les hooks visuels, les variantes. Idéal pour les marques DTC qui veulent du volume créatif testable.",
          "L'influenceur reconverti : a une audience, photogénique, mais souvent moins à l'aise sur l'angle paid pur. Idéal quand vous voulez aussi profiter d'une publication organique.",
        ]},
        { type: "p", text: "Aucune de ces familles n'est meilleure dans l'absolu : la bonne dépend de votre objectif. Pour scaler un compte Meta sur une offre simple, un créateur-monteur fera mieux. Pour défendre une promesse complexe ou émotionnelle, un créateur-comédien sera plus juste." },
        { type: "h2", text: "Oubliez le nombre d'abonnés" },
        { type: "p", text: "Un créateur UGC n'a pas besoin d'audience : il produit du contenu que vous diffusez. Un profil à 2 000 abonnés peut filmer infiniment mieux qu'un compte à 200 000. Le nombre d'abonnés mesure l'influence, pas la capacité à créer un bon asset." },
        { type: "p", text: "Pire : un créateur très suivi vous coûtera souvent plus cher au nom d'une audience que vous n'allez pas utiliser, puisque vous diffusez la vidéo dans vos propres campagnes. Le seul cas où la portée du créateur compte, c'est si vous voulez activer une publication organique sur son compte en parallèle — ce qui relève de l'influence, pas de l'UGC stricto sensu." },
        { type: "h2", text: "Regardez le hook, pas la production" },
        { type: "p", text: "Dans son portfolio, ne vous laissez pas séduire par les belles images. Regardez comment il ouvre ses vidéos. Sait-il accrocher en deux secondes ? Varie-t-il ses angles ? C'est là que se joue la performance, bien plus que dans l'étalonnage." },
        { type: "quote", text: "Un beau plan ne sauve jamais une mauvaise accroche." },
        { type: "p", text: "Pour évaluer concrètement, regardez le portfolio sans le son. Si vous restez accroché — si vous comprenez l'angle, si l'image vous retient — le créateur sait construire un hook visuel. Si l'attention décroche dès la première seconde, l'esthétique générale ne compensera pas, et l'algorithme non plus." },
        { type: "h2", text: "Évaluez la prise de parole" },
        { type: "p", text: "L'UGC repose souvent sur du face caméra. La diction, l'aisance, la capacité à paraître sincère sans réciter : ce sont des compétences d'acteur autant que de créateur. Demandez à voir une vidéo parlée, pas seulement des plans produits muets." },
        { type: "p", text: "Un bon test : demandez au créateur d'enregistrer trente secondes d'auto-présentation, en disant ce qu'il pense de votre produit après l'avoir reçu. Vous saurez en un coup d'œil s'il est à l'aise, s'il improvise correctement, et si sa voix porte. Beaucoup de mauvais castings auraient été évités si l'acheteur avait demandé ces trente secondes avant de signer." },
        { type: "h2", text: "Le casting selon votre audience cible" },
        { type: "p", text: "Le meilleur créateur du monde sera contre-productif s'il ne ressemble pas à votre audience cible. C'est l'une des erreurs les plus fréquentes : choisir un créateur séduisant pour la marque, qui n'incarne pas le client réel." },
        { type: "p", text: "Le test est simple. Posez-vous la question : la personne à l'écran ressemble-t-elle à mes acheteurs sur Meta ? Parle-t-elle leur langue ? Si vous vendez un soin pour cheveux frisés à des femmes de 35 ans, un créateur de 22 ans aux cheveux lisses, même excellent techniquement, fera baisser votre taux de hook. L'algorithme ne pardonne pas l'incohérence." },
        { type: "p", text: "Castez donc moins « la plus belle créa possible » et plus « la créa qui ressemble au prospect ». C'est cet alignement qui fait baisser le CPM et monter le ROAS, pas la qualité de l'image." },
        { type: "h2", text: "Les critères qui comptent vraiment" },
        { type: "ul", items: [
          "Qualité du hook et variété des angles dans le portfolio.",
          "Aisance face caméra et naturel de la prise de parole.",
          "Adéquation visuelle avec votre audience cible.",
          "Clarté sur les droits, les délais et le process.",
          "Capacité à proposer, pas seulement à exécuter.",
          "Réactivité et professionnalisme dès les premiers échanges.",
        ]},
        { type: "h2", text: "Les signaux qui doivent vous faire fuir" },
        { type: "p", text: "Refuser quelques candidatures vous fera économiser des semaines. Voici les drapeaux rouges les plus fiables." },
        { type: "ul", items: [
          "Portfolio composé uniquement de plans produit muets et stylisés — pas de face caméra.",
          "Aucune mention des droits paid dans le devis, ou refus de les inclure.",
          "Tarif unique et fixe quel que soit le brief — pas de cadrage du périmètre.",
          "Délais de réponse longs et changeants dès la phase commerciale.",
          "Discours générique « je crée du contenu UGC » sans mention d'angle, de hook, ou de stratégie.",
        ]},
        { type: "p", text: "Aucun de ces signaux n'est rédhibitoire isolément, mais leur cumul l'est. Un créateur sérieux coche au moins quatre points positifs avant même le brief." },
        { type: "h2", text: "Le test du premier échange" },
        { type: "p", text: "La façon dont un créateur répond à votre première prise de contact en dit long. Pose-t-il des questions sur votre objectif et votre cible, ou saute-t-il directement au prix ? Un bon créateur cadre avant de chiffrer — c'est le meilleur indicateur de la qualité du travail à venir." },
        { type: "p", text: "Si vous hésitez, demandez un appel court. En quinze minutes, on voit immédiatement si la personne comprend les enjeux d'une campagne ou si elle se contente de tenir une caméra. Pour mes propres prospects, c'est cet appel — gratuit, sans engagement — qui sert de filtre dans les deux sens. Si vous voulez le faire avec moi, le lien est sur la page d'accueil." },
      ],
    },
    en: {
      title: "How to choose your UGC creator without getting it wrong",
      dek: "Follower count tells you nothing about a UGC creator's quality. Here are the real criteria to look at before signing a brief.",
      body: [
        { type: "p", text: "The UGC market has exploded, and with it the number of profiles presenting themselves as creators. They're not all equal — and the signals that matter aren't the ones you look at first. Here's how to sort them." },
        { type: "p", text: "Most casting mistakes come from one misunderstanding: people look for a UGC creator the way they used to look for an influencer five years ago — same instincts (followers, feed aesthetics, engagement). But the two jobs aren't measured by the same signals. What makes the difference isn't reach, it's the ability to produce assets that perform in paid." },
        { type: "p", text: "This guide walks through the real criteria — the profile types you'll meet in France, the qualities to test in a portfolio, the red flags that should make you walk away — so you can choose a UGC creator who creates value, not frustration." },
        { type: "h2", text: "The three UGC creator profiles you'll meet in France" },
        { type: "p", text: "Before looking at a portfolio, place the profile. In France in 2026, three broad families share the market, each answering different needs." },
        { type: "ul", items: [
          "The actor-creator: comes from acting, comfortable on camera, strong on delivery and emotion. Ideal for testimonials, spoken demos, sincere claims.",
          "The editor-creator: comes from post-production, strong on pacing, visual hooks, variants. Ideal for DTC brands that want testable creative volume.",
          "The reconverted influencer: has an audience, photogenic, but often less sharp on pure paid angles. Ideal when you also want an organic post on their account.",
        ]},
        { type: "p", text: "No family is better in absolute terms: the right one depends on your goal. To scale a Meta account on a simple offer, an editor-creator will do better. To carry a complex or emotional promise, an actor-creator will be more accurate." },
        { type: "h2", text: "Forget follower count" },
        { type: "p", text: "A UGC creator needs no audience: they produce content you distribute. A profile with 2,000 followers can film infinitely better than an account with 200,000. Follower count measures influence, not the ability to create a good asset." },
        { type: "p", text: "Worse: a heavily followed creator often costs more for an audience you won't use, since the video runs in your own campaigns. The only case where their reach matters is if you want a parallel organic post on their account — which is influencer marketing, not UGC strictly speaking." },
        { type: "h2", text: "Look at the hook, not the production" },
        { type: "p", text: "In their portfolio, don't be seduced by pretty images. Watch how they open their videos. Can they hook you in two seconds? Do they vary their angles? That's where performance is decided, far more than in the color grade." },
        { type: "quote", text: "A beautiful shot never saves a weak opener." },
        { type: "p", text: "Concrete test: watch the portfolio without sound. If you stay hooked — if you grasp the angle, if the image holds you — the creator knows how to build a visual hook. If attention drops in the first second, polished aesthetics won't compensate, and neither will the algorithm." },
        { type: "h2", text: "Assess the delivery" },
        { type: "p", text: "UGC often rests on talking to camera. Diction, ease, the ability to seem sincere without reciting: these are acting skills as much as creator skills. Ask to see a spoken video, not just silent product shots." },
        { type: "p", text: "Good test: ask the creator to record a thirty-second self-introduction, sharing what they think of your product after receiving it. You'll know at a glance whether they're at ease, whether they improvise well, and whether their voice carries. Many bad castings would have been avoided if the buyer had asked for those thirty seconds before signing." },
        { type: "h2", text: "Casting by target audience" },
        { type: "p", text: "The best creator in the world will work against you if they don't look like your target audience. It's one of the most frequent mistakes: picking a creator who flatters the brand but doesn't embody the actual customer." },
        { type: "p", text: "The test is simple. Ask yourself: does the person on screen look like my Meta buyers? Do they speak their language? If you sell curly-hair care to women in their thirties, a 22-year-old creator with straight hair — even technically brilliant — will tank your hook rate. The algorithm doesn't forgive incoherence." },
        { type: "p", text: "So cast less for \"the best possible creative\" and more for \"the creative that looks like the prospect.\" That alignment is what lowers CPM and lifts ROAS, not image quality." },
        { type: "h2", text: "The criteria that really matter" },
        { type: "ul", items: [
          "Hook quality and variety of angles in the portfolio.",
          "Ease on camera and natural delivery.",
          "Visual fit with your target audience.",
          "Clarity on rights, deadlines and process.",
          "Ability to propose, not just execute.",
          "Responsiveness and professionalism from the first exchanges.",
        ]},
        { type: "h2", text: "Red flags that should make you walk away" },
        { type: "p", text: "Turning down a few applications will save you weeks. The most reliable red flags:" },
        { type: "ul", items: [
          "Portfolio made only of silent, stylised product shots — no face-to-camera.",
          "No mention of paid rights in the quote, or refusal to include them.",
          "Flat single price regardless of the brief — no scoping of the work.",
          "Long, erratic response times even at the commercial stage.",
          "Generic pitch \"I create UGC content\" with no mention of angle, hook or strategy.",
        ]},
        { type: "p", text: "None of these signals is disqualifying in isolation, but stacking them is. A serious creator ticks at least four positive boxes before the brief even starts." },
        { type: "h2", text: "The first-exchange test" },
        { type: "p", text: "How a creator responds to your first contact says a lot. Do they ask about your goal and target, or jump straight to price? A good creator scopes before pricing — it's the best indicator of the quality of work to come." },
        { type: "p", text: "If you're hesitating, ask for a short call. In fifteen minutes you immediately see whether the person understands a campaign's stakes or just holds a camera. For my own prospects, that call — free, no commitment — works as a filter both ways. If you want to do it with me, the link is on the home page." },
      ],
    },
  },

  {
    slug: "formats-ugc-meta-ads",
    category: { fr: "Formats", en: "Formats" },
    dateISO: "2026-07-08",
    readMin: 6,
    hero: "META ADS / FORMATS",
    fr: {
      title: "Les formats UGC qui performent le mieux sur Meta Ads",
      dek: "Tous les UGC ne se valent pas en paid. Voici les formats qui font baisser le coût par acquisition sur Facebook et Instagram — et comment les structurer.",
      body: [
        { type: "p", text: "Sur Meta, l'enchère récompense la rétention et le taux de clic. Un UGC qui « plaît » mais ne retient pas est un mauvais asset. Voici les formats qui, structurellement, performent le mieux en feed et en stories." },
        { type: "h2", text: "Le testimonial problème → solution" },
        { type: "p", text: "Le format le plus fiable. On ouvre sur un problème concret que vit la cible, on introduit le produit comme résolution, on termine sur la preuve. Il fonctionne parce qu'il épouse exactement le parcours mental de l'acheteur." },
        { type: "h2", text: "Le « 3 raisons » / listicle" },
        { type: "p", text: "Énumérer trois raisons d'acheter, ou trois choses qu'on aurait aimé savoir, structure l'attention et invite à rester jusqu'au bout. Idéal pour densifier l'information sans perdre le rythme." },
        { type: "h2", text: "Le unboxing / first impression" },
        { type: "p", text: "La découverte en direct crée une tension narrative simple : qu'y a-t-il dedans, est-ce à la hauteur ? Très efficace pour les produits physiques où l'objet lui-même est désirable." },
        { type: "quote", text: "Le bon format ne décore pas le message : il épouse la façon dont l'acheteur pense." },
        { type: "h2", text: "Les principes qui priment sur le format" },
        { type: "ul", items: [
          "Un hook dans les deux premières secondes, visuel et verbal.",
          "Du texte à l'écran : 80 % regardent sans le son.",
          "Vertical plein cadre, jamais de bandes noires.",
          "Un seul message par vidéo — une seule promesse, un seul CTA.",
          "Plusieurs variations de hook sur un même corps de vidéo.",
        ]},
        { type: "h2", text: "Structurer pour le test" },
        { type: "p", text: "La meilleure pratique n'est pas de chercher LE format gagnant, mais d'en produire plusieurs et de laisser l'algorithme trancher. Un même tournage doit générer assez de variations pour alimenter plusieurs ad sets — c'est là que l'UGC déploie tout son intérêt en paid." },
        { type: "p", text: "Concrètement : pour une campagne Meta, je recommande de partir avec au moins deux formats différents et trois hooks par format. De quoi identifier rapidement la combinaison qui fait baisser le coût par acquisition." },
      ],
    },
    en: {
      title: "The UGC formats that perform best on Meta Ads",
      dek: "Not all UGC performs equally in paid. Here are the formats that lower cost per acquisition on Facebook and Instagram — and how to structure them.",
      body: [
        { type: "p", text: "On Meta, the auction rewards retention and click-through. A UGC that's \"likeable\" but doesn't retain is a bad asset. Here are the formats that structurally perform best in feed and stories." },
        { type: "h2", text: "The problem → solution testimonial" },
        { type: "p", text: "The most reliable format. Open on a concrete problem the target lives with, introduce the product as the resolution, close on proof. It works because it mirrors the buyer's mental journey exactly." },
        { type: "h2", text: "The \"3 reasons\" / listicle" },
        { type: "p", text: "Listing three reasons to buy, or three things you wish you'd known, structures attention and invites viewers to stay to the end. Ideal for packing in information without losing pace." },
        { type: "h2", text: "The unboxing / first impression" },
        { type: "p", text: "Live discovery creates a simple narrative tension: what's inside, does it live up to it? Very effective for physical products where the object itself is desirable." },
        { type: "quote", text: "The right format doesn't decorate the message: it mirrors how the buyer thinks." },
        { type: "h2", text: "The principles that outrank the format" },
        { type: "ul", items: [
          "A hook in the first two seconds, visual and verbal.",
          "On-screen text: 80% watch without sound.",
          "Full-frame vertical, never letterboxed.",
          "One message per video — one promise, one CTA.",
          "Several hook variations on the same video body.",
        ]},
        { type: "h2", text: "Structuring for testing" },
        { type: "p", text: "Best practice isn't to hunt for THE winning format, but to produce several and let the algorithm decide. A single shoot should generate enough variations to feed multiple ad sets — that's where UGC delivers its full value in paid." },
        { type: "p", text: "Concretely: for a Meta campaign, I recommend starting with at least two different formats and three hooks per format. Enough to quickly identify the combination that lowers cost per acquisition." },
      ],
    },
  },

  {
    slug: "ugc-ecommerce-fiches-produit",
    category: { fr: "E-commerce", en: "E-commerce" },
    dateISO: "2026-07-22",
    readMin: 5,
    hero: "E-COMMERCE / PREUVE",
    fr: {
      title: "UGC & e-commerce : pourquoi vos fiches produit ont besoin de vrais clients",
      dek: "Vos visuels packshot rassurent sur le produit. Ils ne rassurent pas sur la décision d'achat. C'est exactement là que l'UGC fait la différence.",
      body: [
        { type: "p", text: "La fiche produit est le moment de vérité de l'e-commerce. C'est là que se joue la conversion, après tout le travail d'acquisition. Et c'est souvent là que tout se grippe : de beaux packshots, une description soignée… et un doute qui reste." },
        { type: "h2", text: "Le packshot répond à la mauvaise question" },
        { type: "p", text: "Un visuel studio montre à quoi ressemble le produit. Mais la question de l'acheteur n'est pas « à quoi ça ressemble » — c'est « est-ce que ça va marcher pour moi ». Le packshot décrit ; l'UGC démontre." },
        { type: "quote", text: "Le packshot montre le produit. L'UGC montre la vie avec le produit." },
        { type: "h2", text: "La preuve par le réel" },
        { type: "p", text: "Une vidéo où une personne réelle utilise le produit, dans un vrai contexte, lève les objections que la fiche texte n'atteint pas : la taille réelle, le rendu en conditions normales, la facilité d'usage. Elle transforme une promesse en démonstration." },
        { type: "h2", text: "Où placer l'UGC sur une fiche" },
        { type: "ul", items: [
          "En vidéo intégrée dans la galerie, juste après les packshots.",
          "En section « avis vidéo » sous la description.",
          "En carrousel de mini-formats sur mobile, là où se fait la majorité des achats.",
        ]},
        { type: "h2", text: "L'effet sur la conversion" },
        { type: "p", text: "Ajouter une vidéo UGC sur une fiche produit agit sur deux leviers à la fois : le temps passé sur la page augmente, et le doute pré-achat diminue. Les deux poussent mécaniquement le taux de conversion vers le haut — et réduisent les retours, puisque l'acheteur sait à quoi s'attendre." },
        { type: "h2", text: "Au-delà de la fiche" },
        { type: "p", text: "Le même asset sert sur la fiche produit, en publicité paid, en email de relance panier et en story. Un seul tournage, plusieurs points de contact : c'est ce qui rend l'UGC particulièrement rentable pour un e-commerce. Vous ne payez pas une vidéo, vous équipez tout un tunnel." },
      ],
    },
    en: {
      title: "UGC & e-commerce: why your product pages need real customers",
      dek: "Your packshots reassure people about the product. They don't reassure people about the decision to buy. That's exactly where UGC makes the difference.",
      body: [
        { type: "p", text: "The product page is e-commerce's moment of truth. It's where conversion is decided, after all the acquisition work. And it's often where everything stalls: beautiful packshots, a careful description… and a lingering doubt." },
        { type: "h2", text: "The packshot answers the wrong question" },
        { type: "p", text: "A studio visual shows what the product looks like. But the buyer's question isn't \"what does it look like\" — it's \"will it work for me.\" The packshot describes; UGC demonstrates." },
        { type: "quote", text: "The packshot shows the product. UGC shows life with the product." },
        { type: "h2", text: "Proof through the real" },
        { type: "p", text: "A video where a real person uses the product, in a real context, lifts the objections a text page can't reach: actual size, look in normal conditions, ease of use. It turns a promise into a demonstration." },
        { type: "h2", text: "Where to place UGC on a page" },
        { type: "ul", items: [
          "As a video embedded in the gallery, right after the packshots.",
          "In a \"video reviews\" section below the description.",
          "As a carousel of micro-formats on mobile, where most purchases happen.",
        ]},
        { type: "h2", text: "The effect on conversion" },
        { type: "p", text: "Adding a UGC video to a product page works on two levers at once: time on page rises, and pre-purchase doubt falls. Both mechanically push conversion up — and reduce returns, since the buyer knows what to expect." },
        { type: "h2", text: "Beyond the page" },
        { type: "p", text: "The same asset serves on the product page, in paid ads, in a cart-recovery email and in a story. One shoot, multiple touchpoints: that's what makes UGC especially profitable for e-commerce. You're not paying for a video, you're equipping a whole funnel." },
      ],
    },
  },

  {
    slug: "modele-brief-ugc",
    category: { fr: "Ressources", en: "Resources" },
    dateISO: "2026-08-05",
    readMin: 5,
    hero: "RESSOURCE / MODÈLE",
    fr: {
      title: "Tout ce qu'un brief UGC doit contenir (modèle inclus)",
      dek: "Un brief clair fait gagner du temps à tout le monde et améliore le résultat. Voici la structure exacte que j'utilise, prête à copier-coller.",
      body: [
        { type: "p", text: "Le meilleur investissement avant un tournage UGC, c'est une heure passée sur le brief. Un document d'une page, structuré, vaut mieux que dix échanges de messages. Voici les huit sections indispensables — et un modèle à reprendre tel quel." },
        { type: "h2", text: "1. L'objectif business" },
        { type: "p", text: "Pas le format, le résultat attendu. Baisser le coût par acquisition ? Lancer un produit ? Réchauffer une audience ? Tout le reste découle de cette ligne." },
        { type: "h2", text: "2. L'audience" },
        { type: "p", text: "Qui regarde, dans quel état d'esprit, avec quelles objections. Plus c'est précis, plus le ton et l'angle seront justes." },
        { type: "h2", text: "3. L'angle et la promesse" },
        { type: "p", text: "Le problème qu'on attaque et la raison d'acheter qu'on met en avant. Une vidéo = un angle = une promesse." },
        { type: "h2", text: "4. Les hooks souhaités" },
        { type: "p", text: "Deux à trois idées d'accroche pour les premières secondes. Le créateur peut en proposer d'autres, mais donner une direction accélère tout." },
        { type: "h2", text: "5. Les points de passage" },
        { type: "p", text: "Ce qui doit absolument être dit ou montré : bénéfice clé, élément différenciant, mentions légales éventuelles." },
        { type: "h2", text: "6. Le ton et les références" },
        { type: "p", text: "Une à deux vidéos de référence valent mille adjectifs. Précisez aussi ce que vous ne voulez surtout pas." },
        { type: "h2", text: "7. Les contraintes de marque" },
        { type: "p", text: "Logo, charte, vocabulaire imposé, ce qu'on ne peut pas promettre. Le cadre dans lequel le créateur est libre." },
        { type: "h2", text: "8. La diffusion et le CTA" },
        { type: "p", text: "Où la vidéo sera diffusée, et l'action attendue. Cela conditionne le rythme, la longueur et la fin." },
        { type: "quote", text: "Un brief tient sur une page. S'il en fait dix, ce n'est plus un brief, c'est un cahier des charges." },
        { type: "h2", text: "Le modèle, prêt à copier" },
        { type: "ul", items: [
          "Objectif business : …",
          "Audience cible : …",
          "Angle / promesse : …",
          "Hooks souhaités (2-3) : …",
          "Points de passage obligés : …",
          "Ton & références : …",
          "Contraintes de marque : …",
          "Diffusion & CTA : …",
        ]},
        { type: "p", text: "Copiez ces huit lignes, remplissez-les, et vous avez un brief meilleur que 90 % de ce que reçoivent les créateurs. Si vous voulez qu'on le remplisse ensemble pour votre prochaine campagne, écrivez-moi." },
      ],
    },
    en: {
      title: "Everything a UGC brief should contain (template included)",
      dek: "A clear brief saves everyone time and improves the result. Here's the exact structure I use, ready to copy and paste.",
      body: [
        { type: "p", text: "The best investment before a UGC shoot is an hour spent on the brief. A structured one-page document beats ten back-and-forth messages. Here are the eight essential sections — and a template you can reuse as-is." },
        { type: "h2", text: "1. The business goal" },
        { type: "p", text: "Not the format, the expected result. Lower cost per acquisition? Launch a product? Warm up an audience? Everything else flows from this line." },
        { type: "h2", text: "2. The audience" },
        { type: "p", text: "Who's watching, in what mindset, with which objections. The more precise, the more accurate the tone and angle." },
        { type: "h2", text: "3. The angle and promise" },
        { type: "p", text: "The problem you attack and the reason to buy you put forward. One video = one angle = one promise." },
        { type: "h2", text: "4. Desired hooks" },
        { type: "p", text: "Two or three opener ideas for the first seconds. The creator can propose others, but giving a direction speeds everything up." },
        { type: "h2", text: "5. The mandatory beats" },
        { type: "p", text: "What absolutely must be said or shown: key benefit, differentiator, any legal mentions." },
        { type: "h2", text: "6. Tone and references" },
        { type: "p", text: "One or two reference videos beat a thousand adjectives. Also specify what you really don't want." },
        { type: "h2", text: "7. Brand constraints" },
        { type: "p", text: "Logo, guidelines, required vocabulary, what can't be promised. The frame within which the creator is free." },
        { type: "h2", text: "8. Distribution and CTA" },
        { type: "p", text: "Where the video will run, and the expected action. This drives the pace, length and ending." },
        { type: "quote", text: "A brief fits on one page. If it runs to ten, it's no longer a brief, it's a spec sheet." },
        { type: "h2", text: "The template, ready to copy" },
        { type: "ul", items: [
          "Business goal: …",
          "Target audience: …",
          "Angle / promise: …",
          "Desired hooks (2-3): …",
          "Mandatory beats: …",
          "Tone & references: …",
          "Brand constraints: …",
          "Distribution & CTA: …",
        ]},
        { type: "p", text: "Copy these eight lines, fill them in, and you have a brief better than 90% of what creators receive. If you'd like to fill it in together for your next campaign, drop me a line." },
      ],
    },
  },
];
