// Bilingual copy for VIDALOZZI
window.COPY = {
  fr: {
    nav: { home: "Accueil", ugc: "UGC", talent: "Talent", contact: "Contact" },
    book: "Réserver un appel",
    home: {
      eyebrow: "Paris · Représenté par Pop Agency & Enjoy Model",
      heroLine1: "L'image",
      heroLine2: "fait foi.",
      heroSub: "Teddy Vidal — créateur de contenu UGC, mannequin et comédien. Une présence éditoriale au service des marques et des directeurs artistiques.",
      pickPath: "Choisissez votre voie",
      ugcCard: {
        eyebrow: "Pour les marques",
        title: "UGC",
        sub: "Contenu authentique, taillé pour la performance. Posts, stories, reels et publicités vidéo qui convertissent.",
        cta: "Voir les services UGC",
      },
      talentCard: {
        eyebrow: "Pour les directeurs artistiques",
        title: "Talent",
        sub: "Mannequin et comédien. Campagnes, éditoriaux, films, fictions. Disponible pour castings et bookings.",
        cta: "Voir le book talent",
      },
      brandsLabel: "Ils m'ont fait confiance",
      aboutLabel: "À propos",
      aboutHead: "Une présence éditoriale, deux territoires.",
      aboutBody: "Formé à l'écran et au studio, je travaille à l'intersection du contenu de marque et de la fiction. UGC le matin pour des marques que j'utilise vraiment, casting l'après-midi pour des projets qui me parlent. La même rigueur, deux livrables différents.",
      stat1: { v: "120+", l: "Vidéos UGC livrées" },
      stat2: { v: "45", l: "Marques accompagnées" },
      stat3: { v: "8", l: "Campagnes nationales" },
      stat4: { v: "2", l: "Agences" },
    },
    ugc: {
      crumb: "UGC · Pour les marques",
      heroLine1: "Du contenu",
      heroLine2: "qui",
      heroLine3: "convertit.",
      heroSub: "Format natif, ton authentique, exécution premium. Je conçois et tourne des UGC qui performent en paid social, sur TikTok, Reels et YouTube Shorts.",
      servicesLabel: "Services",
      servicesHead: "Ce que je livre.",
      services: [
        { n: "01", t: "UGC Classique", d: "Vidéos verticales authentiques (15-60s), parlées caméra, démonstration produit, unboxing, testimonial." },
        { n: "02", t: "UGC Publicité", d: "Hooks taillés pour le paid, scripts itératifs, 3-5 variations par concept, livrables prêts à diffuser." },
        { n: "03", t: "Photo Lifestyle", d: "Photos UGC en situation, formats stories et feed, retouches naturelles." },
        { n: "04", t: "Voix-off & Narration", d: "Narration en français pour vos contenus, voix posée, ton éditorial ou complice." },
        { n: "05", t: "Concept & Script", d: "Idéation, écriture de scripts, repérage d'insights consommateur, recommandations de hooks." },
        { n: "06", t: "Whitelisting & Droits", d: "Cession de droits étendue, whitelisting Meta, usage paid négocié à la prestation." },
      ],
      packsLabel: "Packs",
      packsHead: "Trois formules. Une exécution.",
      addonsLabel: "Add-on",
      addons: [
        { n: "Script / concept (si Essentiel)", p: "+150€" },
        { n: "Droits paid 30 jours", p: "+50€ / vidéo" },
        { n: "Droits paid 3 mois", p: "+120€ / vidéo" },
        { n: "Droits paid 6 mois", p: "+200€ / vidéo" },
        { n: "Droits paid 12 mois", p: "+350€ / vidéo" },
        { n: "Whitelisting Meta", p: "+300€ / mois" },
        { n: "Rush 48h", p: "+30% du total" },
        { n: "Footage brute", p: "+150€" },
        { n: "Hook / CTA supplémentaire", p: "+75€ / unité" },
        { n: "Multi-personnes (couple, duo)", p: "+200€ / vidéo" },
        { n: "Micro-trottoir / casting figurants", p: "Sur devis" },
      ],
      packs: [
        { name: "Essentiel", price: "À partir de 500€", desc: "Vous arrivez avec votre brief. Je me charge de l'exécution.", features: ["1 vidéo (15-30s), format vertical", "Script & brief fournis par la marque", "2 révisions incluses", "Droits publicitaires 6 mois (paid & organique)", "Livraison sous 5 jours ouvrés"] },
        { name: "Performance", price: "À partir de 1 400€", desc: "Concept, scripts et production — je gère l'intégralité de la création.", features: ["3 vidéos (15-45s), format vertical", "Concept créatif + scripts rédigés par mes soins", "Multi-hooks A/B (2 hooks par vidéo)", "2 révisions par vidéo", "Droits publicitaires 12 mois (paid & organique)", "Livraison sous 8 jours ouvrés"], featured: true },
        { name: "Campagne", price: "Sur devis", desc: "Un partenariat complet, pensé pour performer en continu.", features: ["5+ vidéos premium", "Voix-off française", "Brief stratégique (angles, cibles, calendrier de diffusion)", "Whitelisting Meta (facturation mensuelle)", "Scripts itératifs sur toute la durée"] },
      ],
      processLabel: "Process",
      processHead: "Comment on travaille.",
      process: [
        { n: "01", t: "Brief", d: "Vous m'envoyez votre produit, votre cible et vos objectifs. Je reviens avec 2-3 angles." },
        { n: "02", t: "Concept", d: "Validation des hooks, du ton, du décor. Un script court, des références claires." },
        { n: "03", t: "Tournage", d: "Je filme chez moi ou en extérieur, lumière naturelle, son propre, plusieurs prises." },
        { n: "04", t: "Livraison", d: "Montage, étalonnage, sous-titres. Vous recevez le master + les variations en 5 à 7 jours." },
      ],
      faqHead: "Questions courantes.",
      faq: [
        { q: "Tu fournis le produit ou je l'envoie ?", a: "L'envoi du produit est à la charge de la marque. " },
        { q: "Quels sont les délais de livraison ?", a: "5 jours ouvrés pour le pack Essentiel, 7 jours pour Performance, à définir pour Campagne. Mode urgent disponible (+30%)." },
        { q: "Les droits paid sont-ils inclus ?", a: "Inclus 12 mois pour le pack Performance et Campagne. En option pour Essentiel (+150€)." },
        { q: "Tu travailles en exclusivité catégorie ?", a: "Oui, sur demande, et facturée. Par défaut je peux refuser les concurrents directs pendant la durée des droits paid." },
        { q: "Sous-titres, voix-off, traduction ?", a: "Sous-titres FR inclus. Voix-off FR incluse selon le pack. Anglais possible en option." },
      ],
    },
    talent: {
      crumb: "Talent · Mannequin & Comédien",
      heroLine1: "Présence",
      heroLine2: "à l'image.",
      heroSub: "Mannequin & comédien basé à Paris. Représenté par Pop Agency (mannequin) et Enjoy Model Paris (commercial / acting). Disponible en castings.",
      portfolioLabel: "Portfolio",
      portfolioHead: "Editorial & campagnes.",
      filmoLabel: "Filmographie",
      filmoHead: "À l'écran.",
      films: [
        { y: "2026", t: "RSF", role: "Comédien", dir: "Si maman nous voyait", type: "PUB" },
        { y: "2026", t: "Toupret", role: "Comédien", dir: "Factum", type: "PUB" },
        { y: "2026", t: "TreesWild", role: "Mannequin", dir: "TreesWild", type: "SHOOTING" },
        { y: "2026", t: "Magicien du possible", role: "Comédien", dir: "Greg Guillotin", type: "COURT" },
        { y: "2025", t: "Paris j'Adore", role: "Mannequin", dir: "Hôtel & Spa 5*", type: "SHOOTING" },
        { y: "2022", t: "Nicolas Champagne", role: "Comédien", dir: "34K Film", type: "PUB" },
        { y: "2022", t: "PCS", role: "Comédien", dir: "The CABS", type: "PUB" },
      ],
      statsLabel: "Fiche talent",
      statsHead: "Mensurations & infos.",
      stats: {
        height: "183 cm",
        chest: "109 cm",
        waist: "80 cm",
        suit: "48 EU",
        shoe: "44 EU",
        hair: "Brun",
        eyes: "Marrons",
        languages: "Français · Espagnol · Anglais",
        skills: "Sport · Permis · Dj",
        location: "Paris · Disponible déplacements",
      },
      agenciesLabel: "Agences",
      agenciesHead: "Représentation.",
      agencies: [
        { name: "Pop Agency", scope: "Mannequin · Mode & Campagnes", contact: "booking@popagency.fr" },
        { name: "Enjoy Model Paris", scope: "Commercial · Comédien", contact: "casting@enjoymodel.com" },
      ],
      pressKit: "Télécharger le press kit (PDF)",
    },
    testimonialsLabel: "Témoignages",
    testimonialsHead: "Ce qu'ils en disent.",
    testimonials: [
      { q: "Teddy comprend une marque en un brief. Le contenu livré performe au-dessus de nos benchmarks paid, à chaque fois.", a: "Léa Marchand", r: "Head of Growth · Maison du Café" },
      { q: "Une présence rare à la caméra. On sent l'acteur derrière le mannequin — exactement ce qu'on cherchait pour la campagne.", a: "Stéphane R.", r: "Directeur artistique · Atelier Hervé" },
      { q: "Process carré, livraison toujours en avance. C'est le genre de collaborateur qu'on rappelle.", a: "Karim B.", r: "Founder · Studio Néon" },
      { q: "Un vrai partenaire créatif. Teddy propose, ajuste, et finit par élever le brief plutôt que simplement l'exécuter. On gagne du temps et de la qualité.", a: "Camille D.", r: "Brand Manager · Maison Lumen" },
    ],
    contact: {
      label: "Travaillons ensemble",
      head: { l1: "Un brief,", l2: "un casting,", l3: "un appel ?" },
      sub: "Pour l'UGC, le moyen le plus rapide est de réserver un créneau Calendly. Pour les castings et projets, passez par les agences ou écrivez-moi directement.",
      ctaCalendly: "Réserver via Calendly",
      ctaPressKit: "Télécharger le press kit",
      emailLabel: "Email direct",
      email: "t.vidalozzi@gmail.com",
      instaLabel: "Instagram",
      insta: "@vidalozzi",
    },
    footer: {
      tagline: "Présence éditoriale.",
      cols: {
        navigate: "Navigation",
        services: "Services",
        contact: "Contact",
      },
      copyright: "© 2026 Vidalozzi · Teddy Vidal · Tous droits réservés",
    },
  },

  en: {
    nav: { home: "Home", ugc: "UGC", talent: "Talent", contact: "Contact" },
    book: "Book a call",
    home: {
      eyebrow: "Paris · Repped by Pop Agency & Enjoy Model",
      heroLine1: "The image",
      heroLine2: "speaks first.",
      heroSub: "Teddy Vidal — UGC creator, model and actor. An editorial presence at the service of brands and creative directors.",
      pickPath: "Choose your path",
      ugcCard: {
        eyebrow: "For brands",
        title: "UGC",
        sub: "Authentic content, built for performance. Posts, stories, reels, and video ads that convert.",
        cta: "See UGC services",
      },
      talentCard: {
        eyebrow: "For creative directors",
        title: "Talent",
        sub: "Model and actor. Campaigns, editorials, films, fiction. Available for castings and bookings.",
        cta: "See talent book",
      },
      brandsLabel: "Trusted by",
      aboutLabel: "About",
      aboutHead: "One editorial presence, two territories.",
      aboutBody: "Trained on screen and in studio, I work at the intersection of branded content and fiction. UGC in the morning for brands I actually use, casting in the afternoon for projects that move me. Same rigor, two different deliverables.",
      stat1: { v: "120+", l: "UGC videos delivered" },
      stat2: { v: "45", l: "Brands worked with" },
      stat3: { v: "8", l: "National campaigns" },
      stat4: { v: "2", l: "Agencies" },
    },
    ugc: {
      crumb: "UGC · For brands",
      heroLine1: "Content",
      heroLine2: "that",
      heroLine3: "converts.",
      heroSub: "Native format, authentic tone, premium execution. I conceive and shoot UGC that performs on paid social, TikTok, Reels and YouTube Shorts.",
      servicesLabel: "Services",
      servicesHead: "What I deliver.",
      services: [
        { n: "01", t: "Classic UGC", d: "Authentic vertical videos (15-60s), spoken to camera, product demos, unboxings, testimonials." },
        { n: "02", t: "Paid Ads UGC", d: "Hooks built for paid, iterative scripts, 3-5 variations per concept, ready-to-air deliverables." },
        { n: "03", t: "Lifestyle Photo", d: "UGC photos in context, story and feed formats, natural retouching." },
        { n: "04", t: "Voiceover", d: "French narration for your content, calm tone, editorial or playful." },
        { n: "05", t: "Concept & Script", d: "Ideation, scriptwriting, consumer-insight scouting, hook recommendations." },
        { n: "06", t: "Whitelisting & Rights", d: "Extended rights, Meta whitelisting, paid usage negotiated per engagement." },
      ],
      packsLabel: "Packs",
      packsHead: "Three packs. One execution.",
      addonsLabel: "Add-on",
      addons: [
        { n: "Script / concept (if Essential)", p: "+€150" },
        { n: "Paid rights 30 days", p: "+€50 / video" },
        { n: "Paid rights 3 months", p: "+€120 / video" },
        { n: "Paid rights 6 months", p: "+€200 / video" },
        { n: "Paid rights 12 months", p: "+€350 / video" },
        { n: "Meta whitelisting", p: "+€300 / month" },
        { n: "Rush 48h", p: "+30% of total" },
        { n: "Raw footage", p: "+€150" },
        { n: "Additional hook / CTA", p: "+€75 / unit" },
        { n: "Multi-talent (couple, duo)", p: "+€200 / video" },
        { n: "Vox pop / extras casting", p: "On quote" },
      ],
      packs: [
        { name: "Essential", price: "From €500", desc: "You come with your brief. I handle the execution.", features: ["1 video (15-30s), vertical format", "Script & brief provided by the brand", "2 revisions included", "Ad rights 6 months (paid & organic)", "Delivery in 5 business days"] },
        { name: "Performance", price: "From €1,400", desc: "Concept, scripts and production — I handle the entire creative process.", features: ["3 videos (15-45s), vertical format", "Creative concept + scripts written by me", "Multi-hooks A/B (2 hooks per video)", "2 revisions per video", "Ad rights 12 months (paid & organic)", "Delivery in 8 business days"], featured: true },
        { name: "Campaign", price: "On quote", desc: "A complete partnership, built to perform continuously.", features: ["5+ premium videos", "French voiceover", "Strategic brief (angles, targets, distribution calendar)", "Meta whitelisting (monthly billing)", "Iterative scripts throughout"] },
      ],
      processLabel: "Process",
      processHead: "How we work.",
      process: [
        { n: "01", t: "Brief", d: "Send me your product, target and goals. I come back with 2-3 angles." },
        { n: "02", t: "Concept", d: "Hooks, tone, set are validated. A short script, clear references." },
        { n: "03", t: "Shoot", d: "I shoot at home or outdoors, natural light, clean sound, multiple takes." },
        { n: "04", t: "Delivery", d: "Edit, color grade, subtitles. You get the master + variations in 5–7 days." },
      ],
      faqHead: "Common questions.",
      faq: [
        { q: "Do you provide the product or do I send it?", a: "The brand ships the product." },
        { q: "What's the delivery time?", a: "5 working days for Essential, 7 for Performance, custom for Campaign. Rush available (+30%)." },
        { q: "Are paid rights included?", a: "Included for 12 months in Performance and Campaign. Optional for Essential (+€150)." },
        { q: "Do you offer category exclusivity?", a: "Yes, on request and billed. By default I can decline direct competitors during paid rights." },
        { q: "Subtitles, voiceover, translation?", a: "FR subtitles included. FR voiceover included per pack. EN possible as an option." },
      ],
    },
    talent: {
      crumb: "Talent · Model & Actor",
      heroLine1: "Presence",
      heroLine2: "on camera.",
      heroSub: "Paris-based model & actor. Represented by Pop Agency (model) and Enjoy Model Paris (commercial / acting). Available for castings.",
      portfolioLabel: "Portfolio",
      portfolioHead: "Editorial & campaigns.",
      filmoLabel: "Filmography",
      filmoHead: "On screen.",
      films: [
        { y: "2026", t: "RSF", role: "Comédien", dir: "Si maman nous voyait", type: "PUB" },
        { y: "2026", t: "Toupret", role: "Comédien", dir: "Factum", type: "PUB" },
        { y: "2026", t: "TreesWild", role: "Mannequin", dir: "TreesWild", type: "SHOOTING" },
        { y: "2026", t: "Magicien du possible", role: "Comédien", dir: "Greg Guillotin", type: "COURT" },
        { y: "2025", t: "Paris j'Adore", role: "Mannequin", dir: "Hôtel & Spa 5*", type: "SHOOTING" },
        { y: "2022", t: "Nicolas Champagne", role: "Comédien", dir: "34K Film", type: "PUB" },
        { y: "2022", t: "PCS", role: "Comédien", dir: "The CABS", type: "PUB" },
      ],
      statsLabel: "Talent sheet",
      statsHead: "Measurements & info.",
      stats: {
        height: "183 cm",
        chest: "109 cm",
        waist: "80 cm",
        suit: "48 EU",
        shoe: "44 EU",
        hair: "Brown",
        eyes: "Brown",
        languages: "French · Spanish · English",
        skills: "Sports · Driving licenses · DJ",
        location: "Paris · Available for travel",
      },
      agenciesLabel: "Agencies",
      agenciesHead: "Representation.",
      agencies: [
        { name: "Pop Agency", scope: "Model · Fashion & Campaigns", contact: "booking@popagency.fr" },
        { name: "Enjoy Model Paris", scope: "Commercial · Actor", contact: "casting@enjoymodel.com" },
      ],
      pressKit: "Download press kit (PDF)",
    },
    testimonialsLabel: "Testimonials",
    testimonialsHead: "What they say.",
    testimonials: [
      { q: "Teddy gets a brand in one brief. Delivered content beats our paid benchmarks every time.", a: "Léa Marchand", r: "Head of Growth · Maison du Café" },
      { q: "Rare presence on camera. You feel the actor behind the model — exactly what we wanted for the campaign.", a: "Stéphane R.", r: "Creative Director · Atelier Hervé" },
      { q: "Tight process, always early on delivery. The kind of collaborator you call back.", a: "Karim B.", r: "Founder · Studio Néon" },
      { q: "A real creative partner. Teddy proposes, adjusts, and ends up elevating the brief rather than just executing it. We gain time and quality.", a: "Camille D.", r: "Brand Manager · Maison Lumen" },
    ],
    contact: {
      label: "Let's work together",
      head: { l1: "A brief,", l2: "a casting,", l3: "a call?" },
      sub: "For UGC, the fastest way is to grab a Calendly slot. For castings and projects, go through the agencies or reach me directly.",
      ctaCalendly: "Book via Calendly",
      ctaPressKit: "Download press kit",
      emailLabel: "Direct email",
      email: "t.vidalozzi@gmail.com",
      instaLabel: "Instagram",
      insta: "@vidalozzi",
    },
    footer: {
      tagline: "Editorial presence.",
      cols: {
        navigate: "Navigate",
        services: "Services",
        contact: "Contact",
      },
      copyright: "© 2026 Vidalozzi · Teddy Vidal · All rights reserved",
    },
  },
};

// Resource accessor — uses inlined blob URLs in standalone bundles,
// falls back to relative paths in dev.
const __res = (id, fallback) => (window.__resources && window.__resources[id]) || fallback;

window.BRANDS = [
  { id: "brand-uber", name: "Uber", src: __res("brand-uber", "assets/logos/uber-logo.png") },
  { id: "brand-ubereats", name: "Uber Eats", src: __res("brand-ubereats", "assets/logos/uber-eats-logo.png") },
  { id: "brand-leapmotor", name: "Leapmotor", src: __res("brand-leapmotor", "assets/logos/leapmotor-logo.png") },
  { id: "brand-spartoo", name: "Spartoo", src: __res("brand-spartoo", "assets/logos/spartoo-logo.png") },
  { id: "brand-adopte", name: "Adopte", src: __res("brand-adopte", "assets/logos/adopte-logo.png") },
  { id: "brand-ouestfrance", name: "Ouest France", src: __res("brand-ouestfrance", "assets/logos/ouest-france-logo.png") },
  { id: "brand-meetic", name: "Meetic", src: __res("brand-meetic", "assets/logos/meetic-logo.png") },
  { id: "brand-ozers", name: "Ozers", src: __res("brand-ozers", "assets/logos/ozers-logo.png") },
  { id: "brand-omame", name: "Oma & Me", src: __res("brand-omame", "assets/logos/oma-and-me-logo.png") },
  { id: "brand-eflexplus", name: "eFlexPlus", src: __res("brand-eflexplus", "assets/logos/eflexplus-logo.png") },
  { id: "brand-lamarqueenmoins", name: "La Marque en Moins", src: __res("brand-lamarqueenmoins", "assets/logos/la-marque-en-moins-logo.png") },
  { id: "brand-nu3", name: "nu3", src: __res("brand-nu3", "assets/logos/nu3-logo.png") },
  { id: "brand-mustache", name: "Mustache", src: __res("brand-mustache", "assets/logos/mustache-logo.png") },
];
